export const TableData: Array<Object> = [{"id": 1, "name": "ITC 1", "owner": "me", "status":"saved"},
{ "id": 3, "name": "ITC 2", "owner": "me", "status":"saved"}, 
{ "id": 4, "name": "ITC 3", "owner": "me", "data":  [{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "aaa", "surname": "aaa", "email": "aaa" },
{ "name": "aa", "surname": "aaaa", "email": "aaaa" },
{ "name": "aaa", "surname": "aa", "email": "aaa" }]}, 
{ "id": 6, "name": "ITC 4", "owner": "me", "data":  [{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "aaa", "surname": "aaa", "email": "aaa" },
{ "name": "aa", "surname": "aaaa", "email": "aaaa" },
{ "name": "aaa", "surname": "aa", "email": "aaa" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" },
{ "name": "ewfwe", "surname": "dsdda", "email": "fewfewf" }
]}, 
{ "id": 8, "name": "ITC 1", "owner": "Mary", "data": [{ "name": "aaa", "surname": "aaa", "email": "aaa" },
{ "name": "ddd", "surname": "dsdsa", "email": "fewfewf" },
{ "name": "fdew", "surname": "dsdefa", "email": "fewfewf" },
{ "name": "fewf", "surname": "dsdea", "email": "fewfewf" }]},
{ "id": 10 , "name": "Form", "owner": "Nane", "data":  [{ "name": "aaa", "surname": "aaa", "email": "aaa" },
{ "name": "ddd", "surname": "dsdsa", "email": "fewfewf" },
{ "name": "fdew", "surname": "dsdefa", "email": "fewfewf" },
{ "name": "fewf", "surname": "dsdea", "email": "fewfewf" }]},
{ "id": 11, "name": "ITC 3", "owner": "Smbat", "data":  [{ "name": "aaa", "surname": "aaa", "email": "aaa" },
{ "name": "ddd", "surname": "dsdsa", "email": "fewfewf" },
{ "name": "fdew", "surname": "dsdefa", "email": "fewfewf" },
{ "name": "fewf", "surname": "dsdea", "email": "fewfewf" }]}]
